name: Daily Quad Monitor

on:
  schedule:
    - cron: '15 20 * * 1-5' # Runs at 4:15 PM Eastern (20:15 UTC) Monday-Friday
  workflow_dispatch: # Allows you to click a button to test it manually

# This forces the older actions to use the new Node 24 backend, silencing the warning
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install libraries
        run: pip install -r requirements.txt

      - name: Run Monitor
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python monitor.py
